### ISSUE TITLE
Sug: Email notifications / Latest posts link / thread status icons + more!

### ISSUE THREAD

**Issue by AstonJ** [rubysherpas/forem#12]
A few quick suggestions as requested by Ryan.

Grouped 1 to 3 where 1 is what I'd consider essential

**Group 1**

**Email notifications** - email sent when a thread someone has posted in has received a reply (with options)

**Latest posts link** - to show the latest posts made on the forum, most of my regular users (who hang around the forum) use the forum this way.

**Thread status icons** - to show if a thread contains new posts/whether you have replied in the thread or not/whether it's a 'hot' thread etc

**Who's viewing forum** - when on the forum homepage, shows how many people are visiting each particular forum. It's surprising how lifeless forum systems feel without this.

**Whos online** - list of people active

**Group 2**

**Who visited today** - list of people who visited in last 24hrs 

_I'll add more as and when I think of em/get time_

**Comment by radar** [comment]
**Email notifications** are easy enough to implement, with the emails being sent out by the forum system using the mail configuration of the main application. How precisely we configure the configure to send out these emails I don't know yet, probably some option in an admin backend somewhere. Users should be able to opt-out of receiving these emails too.

"v2" of this feature would allow users to opt-out of the emails on a per-forum basis. Or you could incorporate that into v1, if you wish.

**Latest posts link** This would only be useful if you could show the latest posts on that forum since the person last looked at that page. I can see how it would be useful though.

**Thread status icons** This is generally how I know if activity has been happening on a forum, but I haven't been on any super-heavy forums yet. The styling of the system is something I have not considered yet, but it should be easy enough to do with the asset pipelining stuff in Rails 3.1, having gems to provide different themes.

**Who's viewing forum** I can see how this would be useful, yes. Doesn't have to be names, just "5 users currently viewing this forum".

**Who's online** This could be useful too, but I don't think it should be a high priority. It's not a function of a forum system that I used a lot. It was more of a "nice to have" thing.

**Who visited  today** Similar to the previous one, but even less of a priority.

Thanks for your feedback, a couple of good places to start!

**Comment by AstonJ** [comment]
Sounds good - get the nuts and bolts sorted first the bells n whistles can come later :)

**Comment by AstonJ** [comment]
Oops - didn't meant to close (silly place to put a close button!)

**Comment by gabrielbaez** [comment]
Email notifications would be awesome to have :)

**Comment by radar** [comment]
I absolutely agree. Would you be able to work on a patch to make this happen? While I have the time to do it now (flying) my laptop is sans battery power. I'm also attending a conference this weekend and as such won't be much good until Tuesday afternoon Australian time.

The way I think it should work is that anybody who creates a topic should be subscribed to that topic. Then anybody who posts to that topic should also be subscribed. They then can opt in or out by clicking a "Subscribe to this topic" link near the reply link.

This would require a new table tracking what users are subscribed to what topics. I would call this model something simple like Subscriber and it would contain two fields for each record: user_id and topic_id. 

I think we should also take care to automatically delete subscriptions for a user if their user record is deleted, otherwise we will run into troubles.

This functionality would also require adding an "notifier email address" configuration option to forem, which people would then set in config/initializers/forem.rb. The mail configuration is dealt with in the application and is absolutely none of our business.

In addition to this functionality, (and if you want me to buy you beer) there will need to be a wiki page set up explaining how to configure forem to send these notification emails and possibly a quick demonstration of how you can override the existing templates, which is just done by basic view overriding.

I think that's all that's needed for now. What do you think?

On 04/11/2011, at 3:04, Gabrielreply@reply.github.com wrote:

> Email notifications would be awesome to have :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/radar/forem/issues/12#issuecomment-2626072

**Comment by gabrielbaez** [comment]
It sounds good to me so far,  I'm not sure if I will have the time. But i did finish the categories support feature :)

**Comment by radar** [comment]
No worries. If I get a spare moment over the weekend I may do the email notifications myself, since it's one of those features a couple of people want.

**Comment by radar** [comment]
Clearly I didn't get a spare moment :) Would someone else care to tackle this?

**Comment by jgadbois** [comment]
I'm needing email notifications too - I can tackle this if no one else is.  @radar, let me know if you want me to do it.

**Comment by AstonJ** [comment]
I started on it @jgadbois (under direction from @radar) I got as far as this: https://github.com/AstonJ/forem/tree/adding-subscriptions I can submit a pull request and you take it from there if you like?

**Comment by jgadbois** [comment]
sure as long as @radar is cool with that.  Would you add the pull request to my fork?

**Comment by AstonJ** [comment]
I'm not sure how to do that so have added it here: https://github.com/radar/forem/pull/97

**Comment by radar** [comment]
@jgadbois: I've merged the awesome changes that Aston's worked hard on into master now. Is there anything you can see to improve?

**Comment by jgadbois** [comment]
When I looked the other day the subscriptions got set up, but emails weren't actually getting set out to subscribers.  I'd like to hook all that up.  I don't think any of the front end for subscribing was there yet either.

**Comment by radar** [comment]
Yup that's correct, Aston was going to work on that next. I think he may be doing that now in his branch. You're also right about there not be a front-end for it. Perhaps you two could work on this together?

**Comment by AstonJ** [comment]
I did start on it: https://github.com/AstonJ/forem/tree/email-notifications but I'm sure I screwed something up as SQLite keeps giving me a BusyException now. 

The email-notifications branch was just my rough attempt tbh, so I really don't mind if you scrap it and go ahead and redo it from scratch @jgadbois. 

I don't mind helping out but just bear in mind I'm very new to this (and so I won't be offended if you'd rather do it yourself - I can always help out on sommin else if need be - I'm sure Ryan will be able to find something else for me to work on, lol).

**Comment by jgadbois** [comment]
I'm happy to take a look, but if you want I can work on the front end subscription stuff if you want to keep working on the emails.

@radar - could you take a look at my other pull request and hopefully get it merged as I screwed up and committed some of that work into master on my fork.

**Comment by radar** [comment]
Which pull request? I don't see one. I see your issue #78, but nothing else.

**Comment by jgadbois** [comment]
https://github.com/radar/forem/pull/79

**Comment by AstonJ** [comment]
Hi guys I've got this far: https://github.com/AstonJ/forem/tree/email-notifications 

In Ryan's book he uses an Observer:

class CommentObserver < ActiveRecord::Observer
  def after_create(comment)
   (comment.ticket.watchers - [comment.user]).each do |user|
      Notifier.comment_updated(comment, user).deliver
end end

But I've used an after_create instead. I think my association is wrong - can you give me some pointers please?

**Comment by radar** [comment]
Closing this one now.

The reasoning is thus:
- Nobody else has requested the other features, and so they're currently "YAGNI".
- We'll deal with feature requests like Rails and Spree do, meaning that if a 'large' number of people request them then we'll do work on them. If they have code attached then we will seriously consider merging it in _provided we get consensus from a majority_.

Ok?

**Comment by AstonJ** [comment]
Sounds good Ryan!
