### ISSUE TITLE
Feature request: separate admin layout

### ISSUE THREAD

**Issue by glebm** [rubysherpas/forem#133]
Most websites already have an admin site. 
It would be real nice to be able to specify a different layout for Forem::Admin controllers

**Comment by radar** [comment]
Couldn't you do this already by calling this inside an initializer of your application:

Forem::Admin::BaseController.layout "admin"

That would set the base controller's layout and the other controllers will inherit from that.

**Comment by glebm** [comment]
This does not work (likely related to isolate_namespace?). 

What works, however, is creating a file under app/layouts/forem/admin/base.html.haml with:

```
= render template: 'layouts/admin'
```

This feels like a hack though.

**Comment by radar** [comment]
Oh, my mistake. That will probably work only on the first request in dev mode. You should wrap it in a to_prepare block like this:

```
Rails.application.config.to_prepare do
  Forem::Admin::BaseController.layout "admin"
end
```

That way, it will always set the layout rather than just doing it once, as initializers are loaded only once, where `to_prepare` callbacks are triggered on every request in development but only once in production!

**Comment by glebm** [comment]
Thanks, worked!

**Comment by radar** [comment]
Great to hear :) If you have any other questions we'd be happy to help.
