### ISSUE TITLE
Subscribe/Unsubscribe links in topics/show don't include forum

### ISSUE THREAD

**Issue by jgadbois** [rubysherpas/forem#137]
```
 <%= link_to t(".subscribe"), subscribe_forum_topic_path(@topic) %>
```

I think should be

```
 <%= link_to t(".subscribe"), subscribe_forum_topic_path(@forum, @topic) %>
```

**Comment by marshallshen** [comment]
I think `<%= link_to t(".subscribe", subscribe_forum_topic_path(@topic) %>` is right since in the method code it specifies what forum the topic object belongs to and it redirects to that forum:
`redirect_to forum_topic_url(@topic.forum, @topic)`
Also the Topic model the one_to_many relationship is specified.

**Comment by jgadbois** [comment]
It's a nested path though, which needs both.

**Comment by jgadbois** [comment]
Looks like your right - passes specs and the test app works.  In my production environment it didn't work for some reason and I had to alter the links.

**Comment by radar** [comment]
You're right in it needing both. Could you submit a patch for this?
