### ISSUE TITLE
Rails 3.0.10 With Forem

### ISSUE THREAD

**Issue by mohamagdy** [rubysherpas/forem#138]
Hello all,
Kindly, would you tell me if Forem is supported in Rails 3.0? And how could I install it?
Thanks in advance!

**Comment by radar** [comment]
Nope, Forem doesn't support Rails 3.0 due to the inability to mount an engine easily inside an application. In 3.0, you basically _need_ to extend the application's routes, which is just a Bad Idea.

I would recommend upgrading your application to Rails 3.1 (which really isn't all that big of an upgrade, really!) and then trying Forem again.

**Comment by mohamagdy** [comment]
Yup, thanks @radar =)
