### ISSUE TITLE
Forum thread ordering not based on last post

### ISSUE THREAD

**Issue by beefsack** [rubysherpas/forem#255]
The best example is the example site at: http://forem.herokuapp.com/forums/1

You'll see the threads aren't chronologically ordered by last post.  Some threads are higher, but they are older than others.  Is this by design or a bug?

**Comment by radar** [comment]
I've not deployed to forem.herokuapp.com in a while. Let me see if a new deploy fixes it.

**Comment by radar** [comment]
HEROKUUUUUUUUUUUU!!!! :angry:

**Comment by beefsack** [comment]
Interestingly enough, the issue is occurring on our forem install, which happens to be on Heroku too!  Perhaps an issue with using PostgreSQL and forem?

An example on our forums: https://www.miniand.com/forums/forums/2

**Comment by radar** [comment]
Heroku still being a bitch. Will look at this later. Have paid work to be doing.

**Comment by radar** [comment]
Do you have a reliable way to reproduce this error locally? Just trying to get a grasp of it.

**Comment by radar** [comment]
And right after I make an idiot of myself by asking if you can provide steps, I find out how it happens. 

Take two topics: **Topic A** and **Topic B**. I first create **Topic A** and then create **Topic B**. **Topic B** is then _correctly_ the latest post. If I reply to **Topic A**, then **Topic B** is _incorrectly_ still the latest post.

Looking into it.

**Comment by radar** [comment]
There is already a test for this inside of `post_spec.rb` "sets topic last_post_at value" but the test is too fast, and so incorrectly passes. The test needs for at least a second to pass between the first post creation and the second post creation.

The bug you're seeing was introduced as a fix for #245 with the commit @46345c4. It's not setting last_post_at because there's a check in the `Post` model that means that last_post_at will only be set if it's nil. This is clear _now_ when I look at the commit that introduced this change. Sorry, I should've spotted it sooner.

Just fixing up the test now and will commit in a sec.

**Comment by radar** [comment]
This is now fixed with @ad618f98b3fc2de86b500c56aca4be1ac99dae9e. If you have topics incorrectly sorted in your database, you will need to write a script to correctly assign the last_post_at field to their last post's created_at date. Sorry that this happened.

**Comment by beefsack** [comment]
Hi radar, it's all good, I just got up and didn't expect it to be fixed so quickly :) thanks for the fix!

I will share my fix script here once I've written it.

**Comment by beefsack** [comment]
Hi, sorry for the slow update.  I updated the forums and they look all good now :) https://www.miniand.com/forums/forums/1

The command I ran in rails console to fix the last post for each topic was `Forem::Topic.all.each {|t| t.last_post_at = t.posts.maximum('created_at'); t.save }`.
