### ISSUE TITLE
Feature request: Delayed_job?

### ISSUE THREAD

**Issue by oliverriechert** [rubysherpas/forem#304]

**Comment by parndt** [comment]
What do you mean?

**Comment by radar** [comment]
@kultus: I am extremely disappointed that you didn't offer a description for this issue. Please be clearer about your intentions in the future.

**Comment by Spaceghost** [comment]
I just met you, and this is crazy, here's my issue, solve it maybe?

**Comment by levibuzolic** [comment]
![delayed_job?](http://cdn.memegenerator.net/instances/400x/26613777.jpg)

**Comment by parndt** [comment]
k, let's no more

**Comment by radar** [comment]
![thread](http://420.thrashbarg.net/i_like_where_this_thread_is_going_ship_heading_into_epic_storm.jpg)

And by "like" I mean "let's please keep this on track". Maybe @kultus has a very good reason for wanting delayed_job as part of his app. Perhaps it was for the email notifications sent out by Forem?

In that case: I would be hesitant to add a feature, since Rails 4 will have a queuing feature which will accomplish this task. Why would we add a feature that would be Very Soon Now(tm) deprecated by a future release of Rails? Seems like a lot of work to cover only a very short period of time.

**Comment by oliverriechert** [comment]
I live in a different time zones ^^

@radar 

Yes for the email notifications.

But you're right with Rails 4

I will wait with the developers still.
