### ISSUE TITLE
Adding members of the group

### ISSUE THREAD

**Issue by bodrovis** [rubysherpas/forem#354]
Hello! I have an issue when trying to add some members to a group via admin area.

I create a new group, then open it for editing and see a form "Members". I enter email of my user (i have Forem.autocomplete_field = "email" in initializer), but then nothing happens. In the console i see that the request is sent to incorrent route like this: "forum/admin/groups/forum/admin/groups/1/members" (so it is actually duplicating). I remember that some months ago it used to work. What can be the cause of this issue?

Thanks!

**Comment by glsignal** [comment]
Come across this one myself. At a quick glance it's the Forem base path echoed into forem.js.erb omitting a leading slash, making it a relative path rather than an absolute one (correct me if I'm wrong - I did notice that it is deliberately stripped).

Adding the slash back in does fix this particular issue, but I'll leave it up to the contributors to decide on the best solution.

**Comment by radar** [comment]
My bad, I should've linked #373 here. There's work in progress on the `members-select2` branch to fix this problem.

**Comment by glsignal** [comment]
Awesome, thanks.
This probably doesn't need to stay open anymore then, if it's being more actively discussed elsewhere.

**Comment by parndt** [comment]
/me jumps on the opportunity to close an issue
