### ISSUE TITLE
updating routes.rb

### ISSUE THREAD

**Issue by JoeGH** [rubysherpas/forem#395]
I am trying to add forem to an already existing rails app. It's actually the sample app from Michael Hartl's railstutorial. 

I've gotten the simple stuff to work like adding main_app to the paths in the layout files.
And now I have forem wrapped by the sample app header and footer. Beautiful.

Now I am getting an error when I try to create a new topic.

I changed my routes.rb file as best as I could, following the instructions.
It looks like this now:

match '/users/sign_in', :to => "sessions#new", :as => "signin"

farther down in the file is my original signin route:
match '/signin', :to 'sessions#new'

Can you help me to correct this error?

RuntimeError in Forem::TopicsController#new
Forem could not determine the sign in path for your application.\

Thanks for your help.

**Comment by radar** [comment]
Hey Joe.

I _think_ this full error should be this:

```
"Forem could not determine the sign in path for your application. Please do one of these things:
1) Define sign_in_path in the config/routes.rb of your application like this:
or; 2) Set Forem.sign_in_path to a String value that represents the location of your sign in form, such as '/users/sign_in'."
```

What this means is that Forem is expecting a sign_in_path method to be available _or_ `Forem.sign_in_path` to be 
set in `config/initializers/forem.rb`. You can do either of these to tell Forem where to find the sign in route. Forem needs this to redirect people who aren't authenticated, so that they can sign in and then be able to create the topic. 

You've called yours `signin_path`. So you _could_ rename this, or set `Forem.sign_in_path = :signin_path` in that initializer if you absolutely need it to be `signin_path`.

Thanks for using Forem :)

**Comment by JoeGH** [comment]
Sorry to be a pain.
I've tried all types of fixes to no avail.

Now I get this error.
undefined method `user_path' for #<#Class:0x9ceadd4:0x9ce94c0>

Extracted source (around line #16):

```
13:                 Account <b class="caret"></b>
14:                 </a>
15.                 <ul class="dropdown-menu">
16:                 <li><%= link_to "Profile", current_user %></li>
17:                 <li><%= link_to "Settings", main_app.edit_user_path(current_user) %></li>
18:                 <li class="divider"></li>
19:                 <li>
```

Shouldn't "resources :users" in the routes.rb create the user_path method?

Appreciate your help.
Thanks.

**Comment by radar** [comment]
Glad to see you got it sovled Joe :)

**Comment by kumardev** [comment]
I did set the path and it was working a few days back  ,but now it throws error . Should i change the gemfile to point from master to a stable version or something ? I am pretty much confused why it isn't working now :(

**Comment by radar** [comment]
@kumardev "It throws error" is a pretty terrible description of your problem. Please put effort into explaining your problems and we will put as much effort into helping you out. Thanks.

**Comment by mijoharas** [comment]
Ok, so I need to do exactly this. following the wiki [here](https://github.com/radar/forem/wiki/Configuration) by adding

```
Forem.sign_in_path = main_app.signin_path
```

throws an error main_app is undefined (in the initialiser).

Fair enough so I find this thread and try

```
Forem.sign_in_path = :signin_path
```

as is suggested above but this throws the error 

```
undefined method `signin_path_url' for #<Forem::TopicsController:0x00000005eaa060>
```

Any suggestions?

**Comment by radar** [comment]
@mhauserr Do you have an application I can look at which reproduces this issue please?

**Comment by mijoharas** [comment]
sure, just created a minimum working example that produces 

```
undefined method `signin_path_url' for #<Forem::TopicsController:0x007f46740b7068>
```

 with the `Forem.sign_in_path = :signin_path` present in the Forem initializer, see [here](https://github.com/mhauserr/forem_example)
let me know if there's any explanation you want (if you run rake db:seed you can sign in as a user with example@example.com and foobar as password)

**Comment by mijoharas** [comment]
also apologies for the quick and dirty example, it has what it needs :)

**Comment by radar** [comment]
Hi @mhauserr, sorry for the delay in replying. I have had a busy couple of weeks. I think what you could do to solve this problem is to get rid of `Forem.sign_in_path` from `config/initializers/forem.rb` and define the sign in route in `config/routes.rb` like this:

``` ruby
get '/signin',  to: 'sessions#new', :as => :new_user_session
```

That way, Forem would automatically know about that route -- since it's opinionated enough to guess that you may be using Devise, and so tries that route first -- and I think that should solve your problem. I just tried doing this very quickly on my machine and it seems to have worked for me.

Please let me know if you encounter any more problems. I should be able to reply a lot quicker now that things are starting to calm down in the run up to Christmas.

**Comment by bodrovis** [comment]
@mhauserr You can take a look at my demo Forem app which I created couple of weeks ago (I used it to demostrate some other concept, but it works fine): https://github.com/bodrovis/tesforem You do not need `Forem.sign_in_path`, just entry for sign in `routes.rb` (in my example I use Devise but thats no matter).

**Comment by mijoharas** [comment]
ok, it looks like both of these solutions are functionally equivalent to what I've done. In each case a new route is added that goes to the correct controller and action. My original solution was to include 

```
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/sign_in',  to: 'sessions#new',         via: 'get'
```

as the second one would be picked up by Forem. The first one is needed as I have a lot of headers and footers etc. that have `main_app.signin_path` (these could all obviously be changed). As you pointed out I could change the second line to 

```
get '/signin',  to: 'sessions#new', :as => :new_user_session
```

but both still need to be included. No problem for me as either way a new path needs to be created (either `new_user_session_path` or `sign_in_path`) but I'm still curious as to why `Forem.sign_in_path = :sign_in_path` doesn't work, as this should solve the problem without the need for an extra path.

Either way, my problem is solved anyway so there's no issue, thanks for the advice @radar and @bodrovis .

**Comment by radar** [comment]
Great to hear @mhauserr :)
