### ISSUE TITLE
"Hidden" topics are not "un-hideable"

### ISSUE THREAD

**Issue by ToadJamb** [rubysherpas/forem#41]
Once a topic is hidden, there does not appear to be a way to make it visible again.

**Comment by radar** [comment]
On what page are you hiding the topic? I'm sure there are tests for hiding and unhiding topics.

**Comment by ToadJamb** [comment]
I'm hiding it on the topic page. Unhiding does work - as long as you do one of two things:
1. Do not navigate away from the topic page for the hidden topic.
2. Remember the id of the hidden topic so that you can "hack" the url thereby allowing you to click the "Show This Topic" link.

I'm saying there is no UI support to unhide a topic once you navigate away from the hidden topic's page. It appears that not even admin's have a way to see a list of hidden topics.

**Comment by radar** [comment]
My mistake: there are tests for hiding topics but no tests for _unhiding_ topics. Would you be able to write a patch for this issue in order to fix that admins cannot access hidden topics _and_ in the process fixing that topics can be made visible again by admins. Tests would be much appreciated also!

Thank you.

**Comment by radar** [comment]
This is fixed in the commit above.

Thank you for reporting it!
