### ISSUE TITLE
Groups have badges

### ISSUE THREAD

**Issue by AustinLMayes** [rubysherpas/forem#438]
I am trying to accomplish a system where I can put users into a group named "Moderator" and they would get a bootstrap badge with the text moderator and the color specified in the groups panel. Then lets say I put the members in a Donor group and they would get the badge as well. I also plan to have their usernames colored by the highest priority  group (priority set in groups panel)  and it would give them that color in post view and in the topics view. I am not asking for this to be implemented just trying to figure out how to do it myself. 

Thanks in advance, Nathan

**Comment by radar** [comment]
This sounds like a good usecase for the [Deface](https://github.com/spree/deface) gem.

In order to do this you would need to replace the `.user` element in `app/views/forem/posts/_post.html.erb` (virtual path for Deface purposes == "forem/posts/_post") with one that displays the badge for a user. I'd recommend reading the Deface docs to work out how to do that. If you can't understand it from the docs, then I can probably help further.

You can do the same thing with the `.byline started-by` element in `app/views/forem/topics/_topic.html.erb` for the topics view.

**Comment by kiranfractal** [comment]
@NathanTheBook, what is that status of badge implementation ?

**Comment by AustinLMayes** [comment]
@kiranfractal I created this for a private about a year ago. Since the code is private I am afraid I can't post here, I can give the steps I took if someone else wants to implement.

I gave each group a  priority, badge color, and badge background field
I added a method to group to sort by priority
I added a method to user to get all groups by priority
I looped through each in a partial extracting the text and background color and using the group's name for the text.

If someone wants to implement, make a new issue.
