### ISSUE TITLE
Does it work with MongoDB ?

### ISSUE THREAD

**Issue by januszm** [rubysherpas/forem#47]
I'm thinking about using forem in application which is based on MongoDB. Will it work without additional changes?

**Comment by radar** [comment]
At current there is no support for MongoDB built into forem. The main thing is that the models that we use are built only for ActiveRecord at the moment rather than MongoDB. 

I think that it would be possible to patch this to load AR models when AR is loaded, and to load MongoDB models when MongoDB is loaded. However, you must be careful to not duplicate the methods across the two modules as any new additional methods for the models would need to be added twice.

So to answer your question shorter: no, but I think it's possible with some patching.

**Comment by impact11** [comment]
Hi Ryan,

We have been able to make Forem work nicely Mongoid without too much monkey patching; however, we did have to take some parts of the controllers and SQL-like things out of it.

We'd love to contribute this back, but am trying to figure out possible ways of merging it in so that it's part of the core rather than some kind of external add-on.

Any thoughts as to how we might be able to abstract some of the database-dependent pieces?

**Comment by radar** [comment]
What database-dependent pieces do you mean?

**Comment by impact11** [comment]
Perhaps not "database-dependent", but rather "database-technology-dependent" (i.e. SQL in code) .

Mostly, it's inside the models. We hadn't looked at the main branch code in a few months, and there were SQL calls in there in a number of places. But now I see that a lot of the SQL syntax that we had stripped out is actually no longer in the main branch - we see there's been a lot of de-sqlification.

There are some Mongoid-specific aspects as well, related to how one has to build embedded documents, or how sorting and selector clauses are defined, when you build the host document which cause some of the controllers to require one or two calls.

Perhaps the key thing to do is just make sure that users who want to use Mongo/Mongoid have a separate set of API-compatible Modules that are transparent to the controllers... which I think the main branch is already close to it, and we're close to it too in our build.

Let me go back to the main branch, do some finessing of our "just make it work code" and see if I can't propose something workable.

**Comment by radar** [comment]
Alright. I look forward to seeing what you can contribute back :)

**Comment by jbredeche** [comment]
Hi @impact11, I'm also trying to get Forem to work with Mongoid/Mongo.  Did you succeed in doing so?  Would love to see what you came up with.

**Comment by impact11** [comment]
Hey there,

Yup, we have it working. We have some app-specific code that we need to
yank out before we publish, and it's forked from an old version (the
upstream merge will be epic) but it's smooth.

I'll see if I can get it cleaned up over the next week to give you a good
starting point.
On Jul 19, 2012 5:53 PM, "jbredeche" <
reply@reply.github.com>
wrote:

**Comment by jbredeche** [comment]
Thanks, very nice of you!

**Comment by impact11** [comment]
We're trying to get our site out into Beta over the next few weeks, so our cycles are a bit tied up, but one of the first things we need to do is take the current implementation of forem-mongoid and update it to the current version of Forem -- we're about 9 months behind. On the plus side, it's not a difficult implementation. I'm hopeful we can make a push out by around October.

**Comment by knewter** [comment]
Would it not be possible to build this as a plugin or overlay on forem
that, when required, made it support mongo rather than activerecord?  If
not, we could consider a more high level strategy for abstracting out the
persistence layer.  I'm of the opinion that leads to better code _anyway_
and I have some experience doing this with plutus (though we've not yet
gotten my company's work on that point merged).

**Comment by impact11** [comment]
I haven't dug into the code for a bit, and there have been
non-insignificant changes in the main branch that may make what I'm writing
inaccurate, but our experience getting forem to work with
ActiveModel/Mongoid pointed to the fact that at the very least, all of the
modules needed to be touched in some way to establish the kinds of
relationships Mongoid supports, and there was some minor amount of
modification to finder/criteria language to make it work reliably.

The ideal approach would be going through all of the finders/criteria
language in the main branch, identifying those that would require a rewrite
to support mongoid, and determine if there is a way of writing them so that
they are ORM-independent.

**Comment by radar** [comment]
Wouldn't you be able to use something like orm_adapter to provide support for both ORMs? I haven't looked into it yet. Just an idea.

**Comment by knewter** [comment]
In general, I prefer to write code these days that is
persistence-mechanism-agnostic.  It's not 'idiomatic' rails and it's a bit
more verbose, but I feel that the resulting code ends up just being
better.  My $0.02

On Thu, Aug 30, 2012 at 1:22 PM, Ryan Bigg notifications@github.com wrote:

> Wouldn't you be able to use something like orm_adapter to provide support
> for both ORMs? I haven't looked into it yet. Just an idea.
> 
> On 30/08/2012, at 18:49, Juan Felipe Rincón notifications@github.com
> wrote:
> 
> > I haven't dug into the code for a bit, and there have been
> > non-insignificant changes in the main branch that may make what I'm
> > writing
> > inaccurate, but our experience getting forem to work with
> > ActiveModel/Mongoid pointed to the fact that at the very least, all of
> > the
> > modules needed to be touched in some way to establish the kinds of
> > relationships Mongoid supports, and there was some minor amount of
> > modification to finder/criteria language to make it work reliably.
> > 
> > The ideal approach would be going through all of the finders/criteria
> > language in the main branch, identifying those that would require a
> > rewrite
> > to support mongoid, and determine if there is a way of writing them so
> > that
> > they are ORM-independent.
> > 
> > On Thu, Aug 30, 2012 at 12:12 PM, Josh Adams notifications@github.comwrote:
> > 
> > > Would it not be possible to build this as a plugin or overlay on forem
> > > that, when required, made it support mongo rather than activerecord?
> > > If
> > > not, we could consider a more high level strategy for abstracting out
> > > the
> > > persistence layer. I'm of the opinion that leads to better code
> > > _anyway_
> > > and I have some experience doing this with plutus (though we've not
> > > yet
> > > gotten my company's work on that point merged).
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/radar/forem/issues/47#issuecomment-8164723>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/radar/forem/issues/47#issuecomment-8169218.

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

**Comment by ronakjain90** [comment]
Do we have a Mongoid Patch or fork available? for forum to work ?

**Comment by radar** [comment]
The answer is still no.

**Comment by skipperguy12** [comment]
Hi, I know this is a bit old but to anyone who was asking for a mongoid version of forem, I've been working on a separate engine modeled after forem for mongoid. Keep in mind, this isn't forem or a fork of forem (although it does borrow a lot of it's code):
https://github.com/NJayDevelopment/mongoid_forums/

It's not 100% complete (I'm open to PRs), but I think that if you were looking for a forum system for mongoid that was similar to forem, this would be fairly good. Here is a demo app (note: this is not the one in test/dummy) if you were curious to see how far along the project is. Feel free to make an account:
http://mongoid-forums.herokuapp.com
