### ISSUE TITLE
Devise User Paths break with Rails 4

### ISSUE THREAD

**Issue by yanismydj** [rubysherpas/forem#478]
I'm using Rails 4 and the rails4 branch of forem.  After installation(which completes successfully), I have a problem using the path helper functions in application.html.erb.  I have a menubar which I render in application.html.erb with the users account link, and log out button, but on the forem pages(/forums, etc) they aren't available.

`undefined local variable or method `my_account_path' for #<#<Class:0x007f9b33bfd850>:0x007f9b3d921550>`

Any ideas about this?

**Comment by radar** [comment]
I'd recommend trying `main_app.my_account_path`. This may be breaking because the template is being rendered within the context of the engine, and the engine does not have a `my_account_path`. Use `main_app` when you want to reference routes from the application and `forem` when you want to reference routes from Forem.

**Comment by yanismydj** [comment]
@radar That was exactly it -- thanks so much dude :+1:  :beer:

**Comment by radar** [comment]
Woot! Glad I could help :)
