### ISSUE TITLE
Import from another forums

### ISSUE THREAD

**Issue by cnaize** [rubysherpas/forem#538]
Hello. What about importing database from another forums? I need to import all database from vBulletin, how to do this?

**Comment by yas375** [comment]
@cnaize you could define model classes for your vBulleting objects and theirs relationships. Probably you will need to define foreign keys and other fields which you don't usually need to specify in rails because of rails' conventions. For example in rails you probably have `user_id` field to store id of the user, but in other systems (i.e. vBulletin) it might be called `uid` or something else.

When you have all needed models defined you could write a rake task which will connect tot vBulletin's database and read all objects and create appropriate objects in your rails application.

Alternatively you could make sql requests to vBulletin's database instead of defining models. But I prefer to manipulate objects instead of plain data.

**Comment by radar** [comment]
Typically a Rake task that reads from your old database, translates the data into a new form, and inserts it into the new database is the right way to go about this. 

It's not something in particular that we can "fix" on Forem so I'm going to go ahead and close this now.
