### ISSUE TITLE
Would be great to have topic voting

### ISSUE THREAD

**Issue by echan00** [rubysherpas/forem#645]
A reddit style voting for most interesting/popular topics would be great

**Comment by jengel3** [comment]
I think that this is better as a separate plugin or gem, but I think forem should remain as the simple parts to a forum.

**Comment by radar** [comment]
Sure, it'd be great on your site. You're free to take forem and modify it to add this feature if you wish. This forem repo won't be getting that feature because not enough people have requested it.

And even if a ton of people requested it, it wouldn't be added until there was a PR that everyone was happy with. That's how this project works.

Thanks for your ideas.
