### ISSUE TITLE
Routes for other controllers not accessable

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [rubysherpas/forem#98]
In my layout I have some user-management stuff (login/logout/etc.) Oddly, that breaks with forem. It can not find the routes to my controller.

``` Ruby
ActionView::Template::Error (No route matches {:action=>"change_persona", :method=>:post, :controller=>"user_sessions"}):
    13:     <%= current_user.email %> 
    14:     <% if current_persona %> 
    15:       as 
    16:       <%= form_tag :controller => '/user_sessions', :method => :post, :action => :change_persona do |f| %>
    17:         <%= collection_select(
    18:         :id, 
    19:         :persona, 
  app/views/layouts/application.html.erb:16:in `_app_views_layouts_application_html_erb___733005464_88044600'
```

Any thoughts here?

**Comment by radar** [comment]
I would strongly advise against using the hash syntax for routes like this, as it leads to problems like this. If you _must_ do this, then do it this way:

```
form_tag main_app.url_for(:controller => user_sessions, :action => :change_persona), :method => :post
```

The `main_app` is the gold here, as that's what's going to tell Forem to go looking for the route in your application rather than inside forem itself, which is what I think is happening here.

If you go down the path of using a routing helper for this, it becomes cleaner:

```
 form_tag main_app.change_persona_path, :method => :post
```

Hope this helps!

**Comment by WhiteFire-Sondergaard** [comment]
Thank you for your quick and educational response! Much appreciated.

**Comment by radar** [comment]
And thank you for at least trying out Forem!

**Comment by crysfel** [comment]
Thanks for the tip
